import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Barbershop",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html suppressHydrationWarning={true} lang="en">
        <body className={`font-sans ${inter.variable} dark`}>
          <TRPCReactProvider>
            <div className="">{children}</div>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
